server.port=8080
  

spring.datasource.url=jdbc:mysql://localhost:3306/ppms?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
  
  # JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
  
  # JWT
security.jwt.secret=0pZhbFOuzzt812sgw5J8JE